name: 'Helm release'
description: 'Build and release Helm packages on S3 repositories.'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  version:
    description: Override Helm chart version.
    required: false
  chart:
    description: The local Helm chart folder path.
    default: './'
    required: true
  repo:
    description: The S3 Helm repository bucket URL.
    required: true
  forceRelease:
    description: Force and replace existing release if a release with the same version already exists.
    default: 'true'
    required: true
  packageExtraArgs:
    description: Helm package command extra arguments.
    required: false
  relativeUrls:
    description: Create the index with relative URLs. Useful for HTTP(S) serving of Helm repos.
    default: 'false'
    required: true
  helmS3Version:
    description: 'The version of the Helm S3 plugin to install. Defaults to the latest release from GitHub.'
    required: false
  runs:
    using: 'docker'
    image: 'Dockerfile'
    env:
      # This block must be correctly indented under 'runs'
      INPUT_VERSION: ${{ inputs.version }}
      INPUT_CHART: ${{ inputs.chart }}
      INPUT_REPO: ${{ inputs.repo }}
      INPUT_FORCERELEASE: ${{ inputs.forceRelease }}
      INPUT_PACKAGEEXTRAARGS: ${{ inputs.packageExtraArgs }}
      INPUT_RELATIVEURLS: ${{ inputs.relativeUrls }}
      INPUT_HELMS3VERSION: ${{ inputs.helmS3Version }}
  # You don't need the `args` section for inputs here,
  # as your Node.js script reads them from the environment
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   args:
#     - ${{ inputs.version }}
#     - ${{ inputs.chart }}
#     - ${{ inputs.repo }}
#     - ${{ inputs.forceRelease }}
#     - ${{ inputs.relativeUrls }}
#     - ${{ inputs.helmS3Version }}  # Ensure it's passed to the script